version: '3.8'
services:
    react-nodejs-example-app:
        image: kiseloff/react-nodejs-example:1.0
        ports:
            - 80:3080
    postgres:
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD:my-pwd
